#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use Template;
use JSON;
use File::Slurp;

my $cfg = decode_json(read_file('dashboard.json'));

foreach (@{$cfg->{modules}}) {
  if (! exists $_->{dist}) {
    $_->{dist} = $_->{name} =~ s/::/-/gr;
  }
  if (! exists $_->{repo}) {
    $_->{repo} = lc $_->{dist};
  }
}

my $tt = Template->new;

$tt->process($cfg->{output}{template}, $cfg, $cfg->{output}{file})
  or die $tt->error;

