#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

use Path::Tiny;
use FindBin '$RealBin';
use lib "$RealBin/lib";
use Dashboard::BranchCache;

my $branch_cache_file = 'repo_def_branch.json';

unless (-f $branch_cache_file) {
  die "Cache file ($branch_cache_file) doesn't exist. Stopping.\n";
}

my $cache = Dashboard::BranchCache->new(file => $branch_cache_file);
$cache->refresh;
$cache->save;
